project_id = "nowfrwpknymkzujijgsz"

[functions.upload-document-init]
verify_jwt = false

[functions.confirm-document-upload]
verify_jwt = false

[functions.process-document]
verify_jwt = false

[functions.classify-case]
verify_jwt = false

[functions.generate-sale-contract]
verify_jwt = false

[functions.accept-service-agreement]
verify_jwt = false

[functions.supabase-mcp-server]
verify_jwt = false

